alerting:
  threema-gateway:
    send-mode: "basic"
    api-base-url: "http://localhost:8090"
    api-identity: "ABCDEFGH"
    recipients:
      - "id:HGFEDCBA"
    auth-secret: "your_auth_secret_here"
    default-alert:
      description: "An alert has been triggered."
      send-on-resolve: true

endpoints:
  - name: endpointname
    group: groupname
    url: "http://doesnotexist.localhost"
    interval: 3s
    conditions:
      - "[STATUS] == 200"
      - "true == true"
    alerts:
      - type: "threema-gateway"
